/**
 * RULE 12 - AN INVALID GROUP MARKER DEGRADES VISIBLY (iugum-39j).
 *
 * Steve, on a real page: "it feels like something is wrong with rendering,
 * when I look at the raw atomdown I don't see the repeats".
 *
 * `_silverbullet/Reference/email-sending-domain-status.md` carried seven
 * atom-group markers with no `id` attribute. Both views resolved which atoms
 * belong to which group BY GROUP ID, so every id-less group collided on one
 * empty key: every atom was attributed to every group, and the inline view
 * emitted the card chrome once per atom-group pair - seven copies of every
 * card, ten groups later ten copies. The bar printed the literal word `null`
 * where the id belongs, and a count of 44 against 50 real atoms. The table
 * bodies rendered once, which is the tell that the duplication is in the
 * group-membership layer rather than in rendering.
 *
 * The document was invalid and the view gave the reader no way to know that.
 * `atomdown lint` reported it correctly; the view never asked. Rendering seven
 * copies is the worst available answer - it looks like OUR defect, and it hid
 * a real document error for days.
 *
 * SO THIS RULE ASSERTS FIVE PROPERTIES, IN BOTH VIEWS:
 *
 *  - 12a  Each card is drawn EXACTLY ONCE, whatever the marker says.
 *  - 12b  The view NAMES the fault in place, with the command that repairs it.
 *  - 12c  The literal string `null` never appears in a group bar.
 *  - 12d  The count in the bar equals the number of cards actually drawn.
 *  - 12e  Not one document byte is written. That is rule 6, and the repair is
 *         `atomdown materialize -w <file>`, which the reader runs, not us.
 *
 * WHY ITS OWN PAGE RATHER THAN THE SHARED FIXTURE. `fixture/running.md` is
 * generated by the real `atomdown materialize`, so it CANNOT hold an invalid
 * marker - that is the point of it, and rule 6 runs `atomdown lint` against
 * it. A document this rule needs is one no repository tool would produce, so
 * each test writes its own page into its own space.
 *
 * THE MARKERS CARRY A SLUG AND NO ID, which is the shape the real page had.
 * A slug-only marker still parses as a group, so the group is drawn and its
 * identity is the thing that is missing. A marker with no attributes at all is
 * not recognised as a group by either view's scanner and is a different
 * defect.
 */

import { test } from "@playwright/test";
import {
  expect,
  gotoFixture,
  openBoard,
  openInline,
  readPageBytes,
  type SBServer,
  settle,
  startSpace,
  type View,
} from "./harness.ts";

const MALFORMED_PAGE = "Todo/malformed";

/**
 * Two groups with a slug and no id, four atoms, two per group.
 *
 * Two is the smallest number that reproduces the collision: one id-less group
 * has nothing to collide with, and the defect scaled with the count (seven
 * groups gave seven copies, ten gave ten).
 */
const MALFORMED_MARKDOWN = [
  '<!-- <atomdown version="1"/> -->',
  "",
  '<!-- <atom-group slug="spf"> -->',
  '<!-- <atom id="AAAAAAAA"/> -->',
  "First atom in the first group.",
  "",
  '<!-- <atom id="BBBBBBBB"/> -->',
  "Second atom in the first group.",
  "<!-- </atom-group> -->",
  "",
  '<!-- <atom-group slug="dkim"> -->',
  '<!-- <atom id="CCCCCCCC"/> -->',
  "First atom in the second group.",
  "",
  '<!-- <atom id="DDDDDDDD"/> -->',
  "Second atom in the second group.",
  "<!-- </atom-group> -->",
  "",
].join("\n");

/** The four atom ids the page holds, in document order. */
const ATOM_IDS = ["AAAAAAAA", "BBBBBBBB", "CCCCCCCC", "DDDDDDDD"];

async function malformedSpace(): Promise<SBServer> {
  return await startSpace({ [`${MALFORMED_PAGE}.md`]: MALFORMED_MARKDOWN });
}

/**
 * The visible text of every group bar in whichever view is open.
 *
 * Read as text rather than as HTML: `null` in a title attribute is not what
 * the reader sees, and 12c is about what the reader sees.
 */
async function groupBarTexts(view: View): Promise<string[]> {
  const bars = view.ev.locator(view.groupHeader);
  const count = await bars.count();
  const out: string[] = [];
  for (let i = 0; i < count; i++) {
    out.push((await bars.nth(i).innerText()).trim());
  }
  return out;
}

/**
 * How many times each atom's card chrome is drawn.
 *
 * The inline view names a card's header widget after the card's box key, and
 * the decoration seam puts that name on the element as `data-decoration-id`.
 * So the count of headers carrying `box:atom:<id>` is exactly how many times
 * that card's chrome was emitted, which is the number the defect multiplied.
 * The board addresses a card by `data-atom-id`.
 */
async function cardChromeCounts(view: View): Promise<Record<string, number>> {
  const out: Record<string, number> = {};
  for (const id of ATOM_IDS) {
    out[id] = view.kind === "inline"
      ? await view.page
        .locator(
          `.sb-decoration-widget.atomdown-card-header[data-decoration-id="box:atom:${id}"]`,
        )
        .count()
      : await view.ev.locator(`.board-card[data-atom-id="${id}"]`).count();
  }
  return out;
}

/** Every card the view drew, however it is addressed. */
async function cardCount(view: View): Promise<number> {
  if (view.kind === "board") {
    return await view.ev.locator(".board-card").count();
  }
  return await view.page
    .locator(".sb-decoration-widget.atomdown-card-header")
    .count();
}

for (const kind of ["inline", "board"] as const) {
  test(`12: ${kind} - an id-less group renders each card once and says what is wrong`, async ({
    page,
  }) => {
    const own = await malformedSpace();
    try {
      const original = await readPageBytes(own, MALFORMED_PAGE);
      await gotoFixture(page, own, MALFORMED_PAGE);
      const view: View = kind === "inline"
        ? await openInline(page)
        : await openBoard(page);
      await settle(page);

      // --- 12a: exactly once ---------------------------------------------
      const chrome = await cardChromeCounts(view);
      for (const id of ATOM_IDS) {
        expect(
          chrome[id],
          `${kind}: card ${id}'s chrome is drawn exactly once`,
        ).toBe(1);
      }
      expect(
        await cardCount(view),
        `${kind}: four atoms produce four cards`,
      ).toBe(4);

      // Two groups, not one merged container and not none. The panel's own
      // collision was different and no worse: it read a null id as "not
      // grouped" and lost the containers entirely.
      const bars = await groupBarTexts(view);
      expect(bars.length, `${kind}: two markers give two group bars`).toBe(2);

      // --- 12b: the fault is named, in place, with the fix ----------------
      const faultSelector = kind === "inline"
        ? ".atomdown-group-fault"
        : ".board-group-fault";
      const faults = view.ev.locator(faultSelector);
      expect(
        await faults.count(),
        `${kind}: each invalid group carries its own notice`,
      ).toBe(2);
      for (let i = 0; i < 2; i++) {
        const text = await faults.nth(i).innerText();
        expect(text, `${kind}: the notice says the group is invalid`).toContain(
          "INVALID GROUP",
        );
        expect(text, `${kind}: the notice says what is missing`).toContain(
          "has no id",
        );
        expect(
          text,
          `${kind}: the notice carries the command that repairs the document`,
        ).toContain("atomdown materialize -w");
        // Visible, not merely present. A notice with no height is the defect
        // back: the reader still sees a page that looks fine.
        await expect(
          faults.nth(i),
          `${kind}: the notice is on screen`,
        ).toBeVisible();
      }

      // --- 12c and 12d: no `null`, and the count is the truth -------------
      for (const bar of bars) {
        expect(
          bar,
          `${kind}: a missing id reads as missing, never as the word null`,
        ).not.toMatch(/\bnull\b/);
        expect(bar, `${kind}: the bar says the id is missing`).toContain(
          "no id",
        );
        expect(
          bar,
          `${kind}: the count equals the two cards this group actually shows`,
        ).toMatch(/\b2\b/);
      }

      // --- 12e: not one byte -----------------------------------------------
      await settle(page, 6);
      await page.waitForTimeout(1500);
      expect(
        await readPageBytes(own, MALFORMED_PAGE),
        `${kind}: the view repaired nothing - rule 6, document immutability`,
      ).toBe(original);

      await view.close();
    } finally {
      await own.stop();
    }
  });
}
