import {chromium} from '../../silverbullet/node_modules/playwright/index.mjs';
import assert from 'node:assert/strict';
const base=process.env.CHIEF_UI_TEST_URL;
if(!base?.startsWith('http://127.0.0.1:'))throw Error('Set isolated CHIEF_UI_TEST_URL');
const browser=await chromium.launch({headless:true});
try{
 const page=await browser.newPage({serviceWorkers:"block",viewport:{width:1440,height:960}});
 let requests=0;
 await page.route('**/.proxy/iugum/api/search?*',async route=>{
  requests++;
  await new Promise(r=>setTimeout(r,350));
  await route.fulfill({json:{transcripts:[{Project:'Fixture transcript',Text:'**Evidence**',html:'<p><strong>Evidence</strong></p><pre><code>one\n  two</code></pre>',Path:'/fixture/session',Session:'test'}],wiki:[{path:'SearchTarget.md',text:'**Wiki**',html:'<p><strong>Wiki</strong></p>'}]}});
 });
 await page.goto(base);await page.getByRole('textbox',{name:'Message agent',exact:true}).waitFor({timeout:60000});
 assert.equal(await page.getByRole('button',{name:'Status',exact:true}).count(),0);
 assert.equal(await page.getByRole('button',{name:'Commitments',exact:true}).count(),0);
 assert.equal(await page.getByRole('button',{name:'Search options',exact:true}).count(),0);
 const scope=page.getByLabel('Source or project scope',{exact:true});assert(await scope.isHidden());
 const compact=await page.locator('#iugum-chief-tools').boundingBox();
 await page.getByRole('searchbox').click();
 await page.getByRole('button',{name:'filters',exact:true}).click();assert(await scope.isVisible(),await page.locator('#iugum-search-options').evaluate(e=>e.outerHTML));
 await scope.fill('wiki');await scope.fill('all');
 await page.getByRole('searchbox').fill('fixture');assert(await scope.isHidden());
 assert.equal((await page.locator('#iugum-chief-tools').boundingBox()).width,compact.width,'search width stays fixed');
 const sources=page.locator('#iugum-search-sources');assert(await sources.isVisible());
 assert.deepEqual(await sources.getByRole('button').allTextContents(),['all','wiki','chats','filters']);
 assert.equal(await sources.getByRole('button',{name:'all',exact:true}).getAttribute('aria-pressed'),'true');
 assert((await sources.boundingBox()).y>compact.y,'source row expands downward');
 const search=page.getByRole('button',{name:'Search',exact:true});
 assert(await search.getAttribute('title'));
 assert.equal(await page.locator('#sb-top #iugum-chief-tools').count(),1);
 const nav=await page.locator('#sb-top').boundingBox(),bar=await page.locator('#iugum-chief-tools').boundingBox();
 assert(Math.abs(bar.x+bar.width/2-(nav.x+nav.width/2))<3,'search centered in whole top nav');
 assert(bar.y>=nav.y && bar.y+bar.height<=nav.y+nav.height+2,'search remains in native nav');
 await search.click();
 const busy=page.getByRole('button',{name:'Searching…',exact:true});
 await busy.waitFor();assert(await busy.isDisabled());
 const results=page.locator('#iugum-chief-results');
 const transcript=results.getByRole('button',{name:'Fixture transcript',exact:true});await transcript.waitFor();
 assert.equal(await results.locator('strong').first().innerText(),'Evidence');
 assert.equal(await results.evaluate(e=>getComputedStyle(e).paddingTop),'18px');
 const rect=await results.boundingBox();
 assert(Math.abs(rect.x-bar.x)<3 && Math.abs(rect.width-bar.width)<4,'results attach to bar');
 assert.equal(await results.locator('article').first().evaluate(e=>getComputedStyle(e).borderTopStyle),'solid');
 const count=requests;
 await page.getByRole('textbox',{name:'Message agent',exact:true}).click();assert(await results.isHidden());
 await page.getByRole('searchbox').click();assert(await results.isVisible());assert.equal(requests,count,'reopen cached results without request');
 await page.getByRole('searchbox').press('Escape');assert(await results.isHidden());
 await page.getByRole('searchbox').click();assert(await results.isVisible());
 await page.screenshot({path:'/private/tmp/chief-nav-search.png'});
 await transcript.click();
 assert.notEqual(await results.locator('details').first().getAttribute('open'),null);
 assert.match(await results.locator('details pre code').first().innerText(),/\n  two/);
 await page.getByRole('button',{name:'Chat',exact:true}).click();
 assert(await results.isHidden());
 assert.equal(await page.getByRole('button',{name:'Chat',exact:true}).getAttribute('aria-pressed'),'false');
 await page.getByRole('button',{name:'Chat',exact:true}).click();
 await page.waitForFunction(()=>[...document.querySelectorAll('.sb-panel')].some(e=>e.shadowRoot?.activeElement?.getAttribute('aria-label')==='Message agent'));
 assert.equal(await page.locator('#iugum-chief-tools').getByRole('button',{name:'Chat',exact:true}).count(),0);
 assert.equal(await page.locator('#iugum-chief-tools').evaluate(e=>getComputedStyle(e).borderTopLeftRadius),'9px');
 assert.equal(await search.evaluate(e=>getComputedStyle(e).borderTopWidth),'0px');
 assert(await page.getByRole('button',{name:'New chat',exact:true}).isEnabled());
 await page.locator('.chief-chat-title').dblclick();
 await page.getByRole('textbox',{name:'Chat title',exact:true}).fill('My renamed conversation');
 await page.getByRole('textbox',{name:'Chat title',exact:true}).press('Enter');
 await page.getByRole('textbox',{name:'Chat title',exact:true}).waitFor({state:'hidden'});
 assert.equal(await page.locator('.chief-chat-title').innerText(),'My renamed conversation');
 await page.locator('.chief-chat-title').dblclick();
 await page.getByRole('textbox',{name:'Chat title',exact:true}).fill('Discard this');
 await page.getByRole('textbox',{name:'Chat title',exact:true}).press('Escape');
 await page.getByRole('textbox',{name:'Chat title',exact:true}).waitFor({state:'hidden'});
 assert.equal(await page.locator('.chief-chat-title').innerText(),'My renamed conversation');
 assert.equal(await page.evaluate(async()=> (await (await fetch('/.proxy/iugum/api/conversation')).json()).title),'My renamed conversation');
 const titleBox=await page.locator('.chief-chat-title').boundingBox();
 const newBox=await page.getByRole('button',{name:'New chat',exact:true}).boundingBox();
 const drawerBox=await page.getByRole('button',{name:'Agents',exact:true}).boundingBox();
 assert(titleBox.x+titleBox.width<=newBox.x+1 && newBox.x<drawerBox.x);
 await page.getByRole('button',{name:'Chat history',exact:true}).click();await page.getByText('Conversation history',{exact:true}).waitFor();
 await page.getByRole('button',{name:'More chat options',exact:true}).click();assert(await page.locator('#iugum-chat-menu-popup').getByRole('menuitem',{name:'Export transcript',exact:true}).isVisible());
 assert(await page.getByRole('menuitem',{name:'Agent settings',exact:true}).isVisible());
 const downloadEvent=page.waitForEvent('download');
 await page.getByRole('menuitem',{name:'Export transcript',exact:true}).click();
 assert.equal((await downloadEvent).suggestedFilename(),'chat-transcript.md');
 await page.getByRole('button',{name:'More chat options',exact:true}).click();
 await page.getByRole('button',{name:'More chat options',exact:true}).click();assert(await page.locator('#iugum-chat-menu-popup').isHidden());
 await page.getByRole('button',{name:'Chat history',exact:true}).click();await page.locator('#iugum-chat-menu-popup').waitFor();
 await page.getByRole('button',{name:'Chat history',exact:true}).click();assert(await page.locator('#iugum-chat-menu-popup').isHidden());
 await search.click();await results.getByRole('button',{name:'SearchTarget.md',exact:true}).click();
 await page.waitForURL('**/SearchTarget');assert(await results.isHidden());
 console.log('Search busy feedback, sanitized-HTML presentation, passage action, wiki navigation, and Chief focus pass.');
}finally{await browser.close()}
