import {chromium} from '../../silverbullet/node_modules/playwright/index.mjs';
import assert from 'node:assert/strict';
const base=process.env.CHIEF_UI_TEST_URL;
if(!base?.startsWith('http://127.0.0.1:'))throw Error('Set isolated CHIEF_UI_TEST_URL');
const browser=await chromium.launch({headless:true});
try{
 const page=await browser.newPage({serviceWorkers:'block',viewport:{width:1200,height:850}});
 const history=[];
 for(let i=0;i<3;i++){
  history.push({role:'user',text:'Prompt '+i,html:'<p>Prompt '+i+'</p>'+('<p>Long prompt context</p>'.repeat(8)),at:'2026-09-12T12:00:00Z'});
  history.push({role:'assistant',text:'Reply',html:'<p>Reply paragraph</p>'.repeat(35),at:'2026-09-12T12:01:00Z'});
 }
 await page.route('**/.proxy/iugum/api/messages',r=>r.fulfill({json:history}));
 await page.goto(base);await page.getByRole('textbox',{name:'Message agent',exact:true}).waitFor({timeout:60000});
 const messages=page.locator('.chief-messages'),users=messages.locator('.user');
 await messages.locator('.chief-turn').nth(2).waitFor();
 assert.equal(await messages.locator('.chief-turn').count(),3);
 const search=page.getByRole('button',{name:'Search',exact:true});assert.equal(await search.locator('svg').count(),1);assert.equal(await search.innerText(),'');
 const promptStyle=()=>users.first().evaluate(e=>({background:getComputedStyle(e).backgroundColor,color:getComputedStyle(e).color,width:e.getBoundingClientRect().width,parentWidth:e.parentElement.getBoundingClientRect().width}));
 let style=await promptStyle();
 assert.equal(style.background,'rgb(231, 242, 255)','default prompt is light blue');
 assert.equal(style.color,'rgb(23, 54, 91)','default prompt text has readable contrast');
 assert(Math.abs(style.width-style.parentWidth)<1,'prompt uses full chat content width');
 // Root theme variables must inherit across the chat shadow boundary.
 await page.evaluate(()=>{document.documentElement.style.setProperty('--iugum-chat-prompt-background','#243447');document.documentElement.style.setProperty('--iugum-chat-prompt-color','#eef6ff');});
 style=await promptStyle();
 assert.equal(style.background,'rgb(36, 52, 71)');assert.equal(style.color,'rgb(238, 246, 255)');
 await page.evaluate(()=>{document.documentElement.style.removeProperty('--iugum-chat-prompt-background');document.documentElement.style.removeProperty('--iugum-chat-prompt-color');});
 await messages.evaluate(e=>{e.scrollTop=400});
 assert.equal(await messages.evaluate(e=>getComputedStyle(e).paddingTop),'0px','no exposed strip above pinned prompt');
 const inset=await messages.evaluate(e=>parseFloat(getComputedStyle(e).paddingTop));
 let bounds=await messages.boundingBox(),first=await users.nth(0).boundingBox();
 assert(Math.abs(first.y-bounds.y-inset)<2,'prompt pins while its reply scrolls '+JSON.stringify({first,bounds}));
 await messages.evaluate(e=>{const t=e.querySelectorAll('.chief-turn')[1];e.scrollTop=t.offsetTop+200;});
 const second=await users.nth(1).boundingBox();first=await users.nth(0).boundingBox();bounds=await messages.boundingBox();
 assert(Math.abs(second.y-bounds.y-inset)<2,'next prompt takes over');assert(first.y+first.height<=bounds.y+inset+2,'previous prompt leaves');
 await users.nth(1).click();
 assert.equal(await users.nth(1).evaluate(e=>getComputedStyle(e).position),'relative');
 assert.equal(await users.nth(1).locator('button').count(),0,'no visible expand button');
 assert.equal(await users.nth(1).locator('.chief-markdown').evaluate(e=>getComputedStyle(e).maskImage),'none');
 await users.nth(1).click();
 assert.equal(await users.nth(1).evaluate(e=>getComputedStyle(e).position),'sticky');
 assert.notEqual(await users.nth(1).evaluate(e=>getComputedStyle(e,'::before').boxShadow),'none','opaque backing masks rounded corners');
 const handle=page.getByRole('separator',{name:'Resize chat'});
 const before=await messages.boundingBox(),grip=await handle.boundingBox();
 await page.mouse.move(grip.x+4,grip.y+100);await page.mouse.down();
 await page.mouse.move(grip.x-100,grip.y+100,{steps:10});await page.mouse.up();
 assert((await messages.boundingBox()).width>before.width+80,'drag widens chat');
 await handle.focus();const wide=await messages.boundingBox();await page.keyboard.press('ArrowRight');
 assert((await messages.boundingBox()).width<wide.width-15,'keyboard resizes chat');
 assert.match(await users.nth(1).locator('.chief-markdown').evaluate(e=>getComputedStyle(e).maskImage),/linear-gradient/);
 assert.match(await users.nth(1).evaluate(e=>getComputedStyle(e,'::after').backgroundImage),/linear-gradient/);
 await users.nth(1).focus();await page.keyboard.press('Enter');assert.equal(await users.nth(1).getAttribute('aria-expanded'),'true');
 await page.keyboard.press('Space');assert.equal(await users.nth(1).getAttribute('aria-expanded'),'false');
 const rail=page.getByRole('navigation',{name:'Conversation navigator'});
 assert.equal(await rail.getByRole('button').count(),3);
 await rail.getByRole('button').nth(2).hover();assert(await page.locator('.chief-turn-preview').isVisible());
 assert.match(await page.locator('.chief-turn-preview').innerText(),/Prompt 2/);
 await rail.getByRole('button').nth(2).click();
 assert.equal(await rail.getByRole('button').nth(2).getAttribute('aria-current'),'true');
 await rail.getByRole('button').first().focus();await page.keyboard.press('Enter');
 assert.equal(await rail.getByRole('button').first().getAttribute('aria-current'),'true');
 assert(await page.locator('.chief-turn-preview').isHidden());
 await page.getByRole('searchbox').focus();await page.mouse.move(10,10);
 const tickWidths=()=>rail.getByRole('button').evaluateAll(items=>items.map(e=>getComputedStyle(e,'::before').width));
 assert.deepEqual(await tickWidths(),['8px','8px','8px']);
 await rail.getByRole('button').nth(1).hover();assert.deepEqual(await tickWidths(),['14px','18px','14px']);
 const hovered=rail.getByRole('button').nth(1),tip=page.locator('.chief-turn-preview');
 const markerBox=await hovered.boundingBox(),tipBox=await tip.boundingBox();
 assert(Math.abs(markerBox.y+markerBox.height/2-tipBox.y-tipBox.height/2)<2,'preview centered beside hovered marker');
 assert.equal(await hovered.evaluate(e=>getComputedStyle(e,'::before').opacity),'1');
 assert.equal(await rail.getByRole('button').first().evaluate(e=>getComputedStyle(e,'::before').opacity),'0.3','hover takes highlight from current turn');
 assert.equal(await rail.getByRole('button').first().evaluate(e=>getComputedStyle(e,'::before').marginLeft),'4px','shorter tick remains right anchored');
 assert.equal(await tip.evaluate(e=>getComputedStyle(e).webkitLineClamp),'5');
 const gapMarker=await rail.getByRole('button').nth(1).boundingBox();
 await page.mouse.move(gapMarker.x+5,gapMarker.y+gapMarker.height+1);
 assert.equal(await rail.getByRole('button').first().evaluate(e=>getComputedStyle(e,'::before').opacity),'0.3','current highlight stays dim between hover targets');
 assert.deepEqual(await tickWidths(),['14px','18px','14px'],'gap retains nearest hover widths');
 assert(await tip.isVisible(),'preview remains visible across gap');
 await page.mouse.move(gapMarker.x+5,gapMarker.y+gapMarker.height+2.5);
 assert.deepEqual(await tickWidths(),['11px','14px','18px'],'hover transfers directly to next tick without reset');
 await page.mouse.move(10,10);
 assert.equal(await rail.getByRole('button').first().evaluate(e=>getComputedStyle(e,'::before').opacity),'1','current highlight returns only outside rail');
 await page.mouse.move(10,10);assert.deepEqual(await tickWidths(),['8px','8px','8px']);
 await page.screenshot({path:'/private/tmp/chief-sticky-preview.png'});
 console.log('Icon accessible; prompts pin within replies, yield to next turn, expand and re-pin.');
}finally{await browser.close()}
